### PR TITLE
Added Splash effect and arranged the folders

### PR DESCRIPTION
**Pull request by hisamov**

### CODE REVIEW

**Comment by serifpersia** [comment]
Issues:
Other modes are broken now. They don't behave as before, there is fade animation to them and there is massive performance issue.Animation mode works as usual.The splash mode works amazingly.
If you are able to fix the modes to the state they were before I don't see why this new mode wouldn't be part of new versions of PianoLED app

**Comment by hisamov** [comment]
Please try new version, effects are fixed now and performance should be better as well

**Comment by serifpersia** [comment]
I noticed few issues still.
Biggest one is performance in modes really.
You hardly can press one or few keys which is not ideal for just basic note on and off for default,random and velocity modes.
Default mode still is very different it only reacts note on, it can't hold the led until you un press the key.
The fade effect is very slow even in your mode it doesn't feel smooth anymore.(maybe because of the default values need to use config parameters to check if its smooth as before)
The rgb sliders are still not working correctly. If you select full red it displays green, if you select full green it displays red, blue works as intended .(edit:adding GRB in addleds line in arduino fixed this. You can use Neopixel or GRB after DATA_PIN, these strips are GRB not RGB)
Animation also works as intended.
I see red compiler errors while you start the app.
The open/close idea is cool. And I like that it gets the devices(my pc has more coms so I still have to select correct com).
I can give you one tip to somehow fix the modes.
They should use note on and note off. Your mode can still use only note on, being able to sense note off as well for that mode will be hard.

**Comment by serifpersia** [comment]
Works well. If are planing to add control for the paramaters of the splash in the UI do it, with that if nothing else breaks  I will merge and close this pull.

**Comment by serifpersia** [comment]
Amazing job. I will accept this pull request now.

**Pull request merged**
